'use client'
import './globals.css'
import "allotment/dist/style.css";
import { Inter } from 'next/font/google'
import { Providers } from '../redux/provider'
import Header from '../components/Header';
const inter = Inter({ subsets: ['latin'] })
import { usePathname } from 'next/navigation';

export const metadata = {
  title: 'Hello',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let Navbar: () => JSX.Element = Header
  const pathname: string = usePathname()

  return (
    <html lang="en">
      <body  suppressHydrationWarning={true} >  <Providers>
        {pathname === '/' ? <> </> : <Navbar /> }
        {children}
        </Providers></body>
    </html>
  )
}
