import "./globals.css";
import "allotment/dist/style.css";
import { Inter } from "next/font/google";
import { Providers } from "../redux/provider";
import Navbar from "../components/Navbar";
import { HeaderProvider } from "../contexts/useHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <HeaderProvider>
            <Navbar />
            {children}
          </HeaderProvider>
        </Providers>
      </body>
    </html>
  );
}
